### PR TITLE
Adding changes from https://github.com/Readify/DevEvents/pull/39

### PR DESCRIPTION
**Pull request by robdmoore**
- Added CFP start/close dates to table
- Added honourable mentions, all-year CFP and TBD lists
- Changed date format to DD-MMM-YYYY
- Crossed out past events
- Added Perth Web Accessibility Camp, Decompress, CampJS

Closes #39 cc @amykapernick @fendersperth

Need to figure out whether to keep the DD/MM/YYYY format (i.e. change back) or change to DD-MMM-YYYY and change CONTRIBUTING.md and the 2017 table...

### CODE REVIEW

**Comment by robdmoore** [comment]
Thoughts on how to approach the date format @ghuntley @alexmackey?

**Comment by alexmackey** [comment]
Looks good to me @robdmoore. I wondered about CFP dates but not sure this will be kept up to date. Meh lets try it and see what happens :) 👍

**Comment by robdmoore** [comment]
Main issue is there is an inconsistent date format now as per my comment - thoughts on which option we use to address that?

--

On 4 Feb 2018, at 10:06 am, Alex Mackey <notifications@github.com<mailto:notifications@github.com>> wrote:


Looks good to me @robdmoore<https://apac01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobdmoore&data=02%7C01%7C%7Cea1b90a1d50346ade4b508d56b73e4fc%7C86ad559a0fdb4325b0a693cb899ec1e5%7C0%7C0%7C636533067872420023&sdata=XfqO8SWhqyAfzpiUZVI3C7NAl3%2F8ewBw9jFnMTQ9JZk%3D&reserved=0>. I wondered about CFP dates but not sure this will be kept up to date. Meh lets try it and see what happens :) 👍

**Comment by alexmackey** [comment]
I know there are other dates to complete but I think I like DD-MMM-YYYY better. Its also clearer if this is used internationally?

I wanted to keep this simple to encourage contributions but also wonder about having this as a json file and some kind of build process to produce the md.

**Comment by tathamoddie** [comment]
ISO 8601. It's clear. It's the international standard for data interchange formats.

yyyy-MM-dd

**Comment by kjacobsen** [comment]
DD-MMM-YYYY is harder to read and seems to format across three lines in my browser. Agree with Tatham that ISO 8601 (yyyy-MM-dd) is a better option.

**Comment by alexmackey** [comment]
The main point of the site however is something for people to read rather than machines (at this point). I know yyyy-MM-dd is not too tricky to read but its not how you would expect to read a date either?

**Comment by tathamoddie** [comment]
I consider it to be a readable format, but that's purely subjective. It supports future parsing and sorting, with a standards alignment, and remains unambiguous when it comes to humans (or machines) reading them.

**Comment by luizbon** [comment]
Giving that this is a page to users and specific to AU, I'd prefer to keep dates as people read in Australia. DD/MM/YYYY
As a user, if I come to any other date format other than that I need to pause and think, which is not a good UX in my POV.
I understand that other formats make our life easier, but we are here to make our life easy and the user experience harder? I'm all favour to the user.

**Comment by robdmoore** [comment]
What about internationals that want to visit an au conference?

--


On 5 Feb 2018, at 10:44 am, Luiz Adilson da Silva Bon <notifications@github.com<mailto:notifications@github.com>> wrote:


Giving that this is a page to users and specific to AU, I'd prefer to keep dates as people read in Australia. DD/MM/YYYY
As a user, if I come to any other date format other than that I need to pause and think, which is not a good UX in my POV.
I understand that other formats make our life easier, but we are here to make our life easy and the user experience harder? I'm all favour to the user.

**Comment by luizbon** [comment]
In that case, the audience is international, not only AU?
Checking international conference websites quickly, all of them use _dd MMMM_. So looks like a pattern to keep the month as name and not numbers.
My opinion is based on having a better user experience instead of easy development, so defining the target audience will help a lot to define what is the best format.

**Pull request merged**
