### PR TITLE
Adds RubyConf AU 2019

### PR DESCRIPTION
**Pull request by philnash**
This kicks off a new 2019 section. Hopefully I put it in the right place. Bring on 2019!

### CODE REVIEW

**Comment by mderriey** [comment]
Thanks @philnash!

Looping @alexmackey @rbanks54 @robdmoore @luizbon in.
Gents, are we happy with having 2019 above 2018? You can check how it looks like here: https://github.com/Readify/DevEvents/blob/37efa39ddecbd5f9bab2cbe219b1aeda119720a4/readme.md

If anyone else has ideas and/or opinions, please fire away ✌

**Comment by philnash** [comment]
Just for a bit more explanation, I added the 2019 section at the top because then the page reads 2019 -> 2018 -> 2017. I'd have thought we'd want to see the newest events at the top so that people don't have to scroll forever to see the upcoming events.

To that point, a more radical reworking would be to reverse the order and show the latest announced events nearer to the top, with 2018 being sorted from December to January.

Could also add month skip links in for each year too, to give each year a table of contents?

What do you think?

**Comment by mderriey** [comment]
I hadn't noticed 2017 was still there.

Does it make sense to keep it?
I'd say no but keen to hear others' opinions.

**Comment by robdmoore** [comment]
Makes sense to split it out to a different file...

**Comment by rbanks54** [comment]
Merging this PR so it's not blocked by us working out how to better organize our content. Raising an issue to psuedo-archive older events.

**Pull request merged**
