### PR TITLE
Add 2019 events and remove some old stuff

### PR DESCRIPTION
**Pull request by alexmackey**
cc: @luizbon @yashints

### CODE REVIEW

**Comment by aaronpowell** [comment]
Is the `Honerable Mentions` stuff needed? It feels like you'd end up duplicating data.

**Comment by alexmackey** [comment]
@aaronpowell its for stuff that doesnt quite fit into the list of events e.g. we had new speaker programs etc and there are likely to be more of these

**Comment by aaronpowell** [comment]
Would they be 'year round' then?

**Comment by luizbon** [comment]
If there's no `Honourable Mentions`, should we have the section at all?

**Comment by alexmackey** [comment]
I dont feel strongly about it and I'll remove for now and can always add back in?

**Pull request merged**
