### PR TITLE
feature: λ

### PR DESCRIPTION
**Pull request by ghuntley**
Added upcoming courses by https://twitter.com/queenslandfplab

### CODE REVIEW

**Comment by mderriey** [comment]
Happy to merge this.

I'd just like to get how people feel about the _[FREE]_ prefix.
I could be overthinking this, but if there's other confs already in there that free but not tagged, it may be misleading.

@alexmackey Any thoughts?

**Comment by alexmackey** [comment]
I'm open to it - I didn't inc pricing info as some confs have complex pricing structures e.g. bronze, silver, gold etc and various early bird discounts. Free however is a simple boolean and would be nice to quickly see those confs that have no cost. 

@mderriey if we were going to introduce now however we would need to mark all the other free conferences to be consistent so suggest remove prefix from this PR?

**Comment by mderriey** [comment]
@alexmackey Thanks for the input.

@ghuntley, are you OK with removing the _[FREE]_ prefix from this PR?
We could tackle this in the future where we tag all the free confs in one go to be consistent.

**Comment by ghuntley** [comment]
👍  🚢

**Pull request merged**
